# -*- coding: utf-8 -*-
# Generated by Django 1.11b1 on 2017-03-16 16:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='In',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jumun', models.CharField(max_length=200)),
                ('type', models.CharField(max_length=200)),
                ('outnums', models.IntegerField(default=0)),
                ('reg_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name=b'Registered Date')),
                ('ans_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name=b'Selected Date')),
                ('content', models.CharField(max_length=200)),
                ('pic0', models.CharField(max_length=200)),
                ('pic1', models.CharField(max_length=200)),
                ('pic2', models.CharField(max_length=200)),
                ('pic3', models.CharField(max_length=200)),
                ('pic4', models.CharField(max_length=200)),
                ('pic5', models.CharField(max_length=200)),
                ('pic6', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Inner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=200)),
                ('nums', models.IntegerField(default=0)),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name=b'Registered Date')),
                ('update', models.DateTimeField(default=django.utils.timezone.now, verbose_name=b'Latest UpDate')),
                ('newnums', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Out',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dapbyun', models.CharField(max_length=200)),
                ('inflag', models.BooleanField(default=False)),
                ('reg_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name=b'Registered Date')),
                ('sel_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name=b'Selected Date')),
                ('content', models.CharField(max_length=200)),
                ('pic0', models.CharField(max_length=200)),
                ('pic1', models.CharField(max_length=200)),
                ('pic2', models.CharField(max_length=200)),
                ('pic3', models.CharField(max_length=200)),
                ('pic4', models.CharField(max_length=200)),
                ('pic5', models.CharField(max_length=200)),
                ('pic6', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Outer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=200)),
                ('nums', models.IntegerField(default=0)),
                ('credits', models.IntegerField(default=0)),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name=b'Registered Date')),
                ('update', models.DateTimeField(default=django.utils.timezone.now, verbose_name=b'Latest UpDate')),
                ('newnums', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='out',
            name='handler',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quots.Outer'),
        ),
        migrations.AddField(
            model_name='out',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quots.In'),
        ),
        migrations.AddField(
            model_name='in',
            name='answered',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='quots.Outer'),
        ),
        migrations.AddField(
            model_name='in',
            name='orderer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quots.Inner'),
        ),
    ]
