# -*- coding: utf-8 -*-
# Generated by Django 1.11b1 on 2017-04-02 09:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quots', '0003_auto_20170402_1826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='in',
            name='orderer',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='quots.Inner'),
        ),
        migrations.AlterField(
            model_name='out',
            name='parent',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='quots.In'),
        ),
    ]
