# -*- coding: utf-8 -*-
# Generated by Django 1.11b1 on 2017-04-02 09:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quots', '0004_auto_20170402_1832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='in',
            name='answered',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='quots.Outer'),
        ),
        migrations.AlterField(
            model_name='out',
            name='handler',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quots.Outer'),
        ),
    ]
