# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-16 11:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('quots', '0006_auto_20170402_1902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='in',
            name='ans_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Selected Date'),
        ),
        migrations.AlterField(
            model_name='in',
            name='reg_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Registered Date'),
        ),
        migrations.AlterField(
            model_name='inner',
            name='email',
            field=models.EmailField(default='devestack@gmail.com', max_length=254, verbose_name='이메일'),
        ),
        migrations.AlterField(
            model_name='inner',
            name='password',
            field=models.CharField(default='null', max_length=30, verbose_name='비밀번호'),
        ),
        migrations.AlterField(
            model_name='inner',
            name='phone',
            field=models.CharField(default='null', max_length=30, verbose_name='휴대전화'),
        ),
        migrations.AlterField(
            model_name='inner',
            name='username',
            field=models.CharField(default='null', max_length=30, verbose_name='아이디'),
        ),
        migrations.AlterField(
            model_name='out',
            name='reg_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Registered Date'),
        ),
        migrations.AlterField(
            model_name='out',
            name='sel_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Selected Date'),
        ),
        migrations.AlterField(
            model_name='outer',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='가입날짜'),
        ),
        migrations.AlterField(
            model_name='outer',
            name='email',
            field=models.EmailField(default='devestack@gmail.com', max_length=254, verbose_name='이메일'),
        ),
        migrations.AlterField(
            model_name='outer',
            name='password',
            field=models.CharField(default='null', max_length=30, verbose_name='비밀번호'),
        ),
        migrations.AlterField(
            model_name='outer',
            name='phone',
            field=models.CharField(default='null', max_length=30, verbose_name='휴대전화'),
        ),
        migrations.AlterField(
            model_name='outer',
            name='update',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='로그인날짜'),
        ),
        migrations.AlterField(
            model_name='outer',
            name='username',
            field=models.CharField(default='null', max_length=30, verbose_name='아이디'),
        ),
    ]
