# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-16 12:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('quots', '0007_auto_20170716_2034'),
    ]

    operations = [
        migrations.AddField(
            model_name='inner',
            name='rname',
            field=models.CharField(default=b'null', max_length=4, verbose_name='\uc608\uae08\uc8fc(\uc2e4\uba85)'),
        ),
        migrations.AddField(
            model_name='outer',
            name='rname',
            field=models.CharField(default=b'null', max_length=4, verbose_name='\uc608\uae08\uc8fc(\uc2e4\uba85)'),
        ),
        migrations.AlterField(
            model_name='outer',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name=b'\xea\xb0\x80\xec\x9e\x85\xeb\x82\xa0\xec\xa7\x9c'),
        ),
        migrations.AlterField(
            model_name='outer',
            name='update',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name=b'\xeb\xa1\x9c\xea\xb7\xb8\xec\x9d\xb8\xeb\x82\xa0\xec\xa7\x9c'),
        ),
    ]
