# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-18 05:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('quots', '0009_auto_20170718_0142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='in',
            name='ans_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='낙찰날짜'),
        ),
        migrations.AlterField(
            model_name='in',
            name='reg_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='등록날짜'),
        ),
        migrations.AlterField(
            model_name='inner',
            name='rname',
            field=models.CharField(default='null', max_length=4, verbose_name='예금주(실명)'),
        ),
        migrations.AlterField(
            model_name='out',
            name='ans_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='낙찰날짜'),
        ),
        migrations.AlterField(
            model_name='out',
            name='reg_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='등록날짜'),
        ),
        migrations.AlterField(
            model_name='outer',
            name='rname',
            field=models.CharField(default='null', max_length=4, verbose_name='예금주(실명)'),
        ),
    ]
