# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-20 17:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quots', '0011_auto_20170720_2139'),
    ]

    operations = [
        migrations.AddField(
            model_name='in',
            name='done',
            field=models.BooleanField(default=False, verbose_name='거래완료'),
        ),
    ]
