# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-21 17:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quots', '0012_in_done'),
    ]

    operations = [
        migrations.AddField(
            model_name='in',
            name='many',
            field=models.IntegerField(default=1, verbose_name='수량'),
        ),
    ]
