# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-24 21:07
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quots', '0017_auto_20170925_0358'),
    ]

    operations = [
        migrations.CreateModel(
            name='Searchedkey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ipaddr', models.CharField(max_length=200, verbose_name='IP주소')),
                ('content', models.CharField(max_length=200, verbose_name='검색내용')),
                ('star', models.CharField(default='null', max_length=30, verbose_name='결과평점')),
                ('gnrs', models.CharField(default='null', max_length=30, verbose_name='장르Top3')),
                ('update', models.DateTimeField(default=django.utils.timezone.now, verbose_name='사용일시')),
                ('isapi', models.BooleanField(default=False, verbose_name='API여부')),
                ('usr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Apicall',
        ),
    ]
