# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-24 22:07
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quots', '0018_auto_20170925_0607'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchedkey',
            name='intent',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='의도'),
        ),
        migrations.AlterField(
            model_name='searchedkey',
            name='update',
            field=models.DateTimeField(default=datetime.date.today, verbose_name='사용일시'),
        ),
        migrations.AlterField(
            model_name='searchedkey',
            name='usr',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
